// scripts/extractRdanaPdfFields.cjs
// Run with: node scripts/extractRdanaPdfFields.cjs

const { PDFDocument } = require('pdf-lib');
const fs = require('fs');
const path = require('path');

async function main() {
  // Adjust this path if your PDF is stored somewhere else
  const pdfPath = path.resolve(
    __dirname,
    '../pdf-templates/RDANA-Form-MDRRMO-fillable.pdf',
  );

  if (!fs.existsSync(pdfPath)) {
    console.error('❌ PDF not found at:', pdfPath);
    console.error('   Adjust the path in extractRdanaPdfFields.cjs if needed.');
    process.exit(1);
  }

  const pdfBytes = fs.readFileSync(pdfPath);
  const pdfDoc = await PDFDocument.load(pdfBytes);
  const form = pdfDoc.getForm();
  const fields = form.getFields();

  /** @typedef {'text' | 'checkbox' | 'radio' | 'other'} GroupKey */

  /** @type {Record<GroupKey, string[]>} */
  const groups = {
    text: [],
    checkbox: [],
    radio: [],
    other: [],
  };

  for (const field of fields) {
    const name = field.getName();
    const ctorName = field.constructor.name; // PDFTextField, PDFCheckBox, PDFRadioGroup, etc.

    /** @type {GroupKey} */
    let kind = 'other';

    switch (ctorName) {
      case 'PDFTextField':
        kind = 'text';
        break;
      case 'PDFCheckBox':
        kind = 'checkbox';
        break;
      case 'PDFRadioGroup':
        kind = 'radio';
        break;
      default:
        kind = 'other';
        break;
    }

    groups[kind].push(name);
  }

  // Sort for deterministic output
  /** @type {GroupKey[]} */
  const keys = ['text', 'checkbox', 'radio', 'other'];
  for (const k of keys) {
    groups[k].sort((a, b) => a.localeCompare(b));
  }

  // Build TypeScript file content
  const outLines = [];

  outLines.push('// AUTO-GENERATED by scripts/extractRdanaPdfFields.cjs');
  outLines.push('// Do not edit by hand.');
  outLines.push('');
  outLines.push('export const RDANA_PDF_FIELDS = {');

  const emitArray = (label, values) => {
    outLines.push(`  ${label}: [`);
    for (const v of values) {
      outLines.push(`    '${v}',`);
    }
    outLines.push('  ],');
  };

  emitArray('texts', groups.text);
  emitArray('checkboxes', groups.checkbox);
  emitArray('radios', groups.radio);
  emitArray('others', groups.other);

  outLines.push('} as const;');
  outLines.push('');

  const outPath = path.resolve(
    __dirname,
    '../src/pdf/rdanaPdfFields.generated.ts',
  );
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, outLines.join('\n'), 'utf8');

  console.log('✅ Extracted RDANA PDF fields to:');
  console.log('   ', outPath);
  console.log('');
  console.log('Counts:', {
    texts: groups.text.length,
    checkboxes: groups.checkbox.length,
    radios: groups.radio.length,
    others: groups.other.length,
  });
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
