// scripts/extractRdanaPdfFields.ts
import { PDFDocument } from 'pdf-lib';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// ESM-safe __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
  const pdfPath = path.resolve(
    __dirname,
    '../pdf-templates/RDANA-Form-MDRRMO-fillable.pdf',
  );

  const pdfBytes = fs.readFileSync(pdfPath);
  const pdfDoc = await PDFDocument.load(pdfBytes);
  const form = pdfDoc.getForm();
  const fields = form.getFields();

  type GroupKey = 'text' | 'checkbox' | 'radio' | 'other';

  const groups: Record<GroupKey, string[]> = {
    text: [],
    checkbox: [],
    radio: [],
    other: [],
  };

  for (const field of fields) {
    const name = field.getName();
    const ctorName = field.constructor.name; // e.g. PDFTextField, PDFCheckBox, PDFRadioGroup

    let kind: GroupKey = 'other';

    switch (ctorName) {
      case 'PDFTextField':
        kind = 'text';
        break;
      case 'PDFCheckBox':
        kind = 'checkbox';
        break;
      case 'PDFRadioGroup':
        kind = 'radio';
        break;
      default:
        kind = 'other';
        break;
    }

    groups[kind].push(name);
  }

  // Sort for deterministic output
  (Object.keys(groups) as GroupKey[]).forEach((k) =>
    groups[k].sort((a, b) => a.localeCompare(b)),
  );

  // Build TS file content
  const outLines: string[] = [];

  outLines.push('// AUTO-GENERATED by scripts/extractRdanaPdfFields.ts');
  outLines.push('// Do not edit by hand.');
  outLines.push('');
  outLines.push('export const RDANA_PDF_FIELDS = {');

  const emitArray = (label: string, values: string[]) => {
    outLines.push(`  ${label}: [`);
    for (const v of values) {
      outLines.push(`    '${v}',`);
    }
    outLines.push('  ],');
  };

  emitArray('texts', groups.text);
  emitArray('checkboxes', groups.checkbox);
  emitArray('radios', groups.radio);
  emitArray('others', groups.other);

  outLines.push('} as const;');
  outLines.push('');

  const outPath = path.resolve(
    __dirname,
    '../src/pdf/rdanaPdfFields.generated.ts',
  );
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, outLines.join('\n'), 'utf8');

  console.log('✅ Extracted RDANA PDF fields to:');
  console.log('   ', outPath);
  console.log('');
  console.log('Counts:', {
    texts: groups.text.length,
    checkboxes: groups.checkbox.length,
    radios: groups.radio.length,
    others: groups.other.length,
  });
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
