// ~/models/pdfFieldMap.ts
export const RDANAFieldMap: Record<string, string> = {
  // Section A
  disaster_type: "disaster_type",
  date_time_occur: "date_time_occur",
  areas_affected: "areas_affected",
  source_of_report: "source_of_report",
  date_time_reports: "date_time_reports",

  // Section B
  affected_popu_families: "affected_popu_families",
  affected_popu_persons: "affected_popu_persons",
  affected_popu_num_infants: "affected_popu_num_infants",
  affected_popu_num_children: "affected_popu_num_children",
  affected_popu_num_adults: "affected_popu_num_adults",
  displaced_popu_families: "displaced_popu_families",
  displaced_popu_persons: "displaced_popu_persons",
  displaced_popu_num_infants: "displaced_popu_num_infants",
  displaced_popu_num_children: "displaced_popu_num_children",
  displaced_popu_num_adults: "displaced_popu_num_adults",
  loc_dead: "loc_dead",
  num_dead: "num_dead",
  cause_dead: "cause_dead",
  loc_injured: "loc_injured",
  num_injured: "num_injured",
  cause_injured: "cause_injured",
  loc_missing: "loc_missing",
  num_missing: "num_missing",
  missing: "missing",

  // Section C
  search_and_rescue_exact_loc: "search_and_rescue_exact_loc",
  sar_approx_num_missing_children: "sar_approx_num_missing_children",
  sar_approx_num_missing_adults: "sar_approx_num_missing_adults",
  evacuation_exact_loc: "evacuation_exact_loc",
  evac_response: "evac_response",
  unmet_needs_evac: "unmet_needs_evac",
  evac_center_names: "evac_center_names",
  approx_num_to_evac_infants: "approx_num_to_evac_infants",
  approx_num_to_evac_children: "approx_num_to_evac_children",
  approx_num_to_evac_adults: "approx_num_to_evac_adults",
  num_of_person_in_evac_in_need_of_assistance: "num_of_person_in_evac_in_need_of_assistance",
  requirement_of_affected_fam_in_evac: "requirement_of_affected_fam_in_evac",

  // Section D (Medical)
  medical_health_exact_loc: "medical_health_exact_loc",
  medical_health_num_injured: "medical_health_num_injured",
  medical_health_unmet_needs: "medical_health_unmet_needs",
  displaced_fam_medic_attention_families: "displaced_fam_medic_attention_families",
  displaced_fam_medic_attention_persons: "displaced_fam_medic_attention_persons",
  displaced_fam_medic_attention_infants: "displaced_fam_medic_attention_infants",
  displaced_fam_medic_attention_children: "displaced_fam_medic_attention_children",
  displaced_fam_medic_attention_adults: "displaced_fam_medic_attention_adults",
  health_care_facilities: "health_care_facilities",
  emergency_health_and_medical_services: "emergency_health_and_medical_services",
  is_there_health_workers: "is_there_health_workers",

  // Section E (Shelter/Food/Water)
  shelter_and_clothing_exact_loc: "shelter_and_clothing_exact_loc",
  num_of_people_shelter_and_clothing_male: "num_of_people_shelter_and_clothing_male",
  num_of_people_shelter_and_clothing_female: "num_of_people_shelter_and_clothing_female",
  num_of_people_food_infants: "num_of_people_food_infants",
  total_num_of_people_food: "total_num_of_people_food",
  num_of_people_food_children: "num_of_people_food_children",
  num_of_people_without_pot_water_infants: "num_of_people_without_pot_water_infants",
  num_of_people_without_pot_water_adult: "num_of_people_without_pot_water_adult",
  num_of_people_without_pot_water_children: "num_of_people_without_pot_water_children",
  water_response_stat: "water_response_stat",
  water_unmet_needs: "water_unmet_needs",
  is_there_water_arrangement: "is_there_water_arrangement",
  restoration_lifelines_exact_loc: "restoration_lifelines_exact_loc",
  restoration_lifelines_condition: "restoration_lifelines_condition",
  restoration_lifelines_unmet_needs: "restoration_lifelines_unmet_needs",

  // Section F (Education / Response)
  is_there_school_damage_yes: "is_there_school_damage_yes",
  num_of_children_affected_by_damage: "num_of_children_affected_by_damage",
  extent_of_disruption: "extent_of_disruption",
  responders_involved: "responders_involved",
  assets_deployed: "assets_deployed",
  num_of_persons_served_families: "num_of_persons_served_families",
  num_of_persons_served_persons: "num_of_persons_served_persons",
  num_of_persons_served_infants: "num_of_persons_served_infants",
  num_of_persons_served_children: "num_of_persons_served_children",
  num_of_persons_served_adults: "num_of_persons_served_adults",
  extent_of_local_assist: "extent_of_local_assist",
  signed: "signed"
}
